version: '3.9'

services:
  app:
    build: .
    container_name: restaurantpos-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurantpos
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

  db:
    image: postgres:16.2
    container_name: restaurantpos-db
    restart: always
    environment:
      POSTGRES_DB: restaurantpos
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d restaurantpos"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: