version: '3.9'

services:
  db:
    image: postgres:16.2
    container_name: restaurantpos-db
    restart: always
    environment:
      POSTGRES_DB: restaurantpos
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
